language: node_js
sudo: required
dist: trusty
services:
  - docker
script:
- docker run -t -i -v "$(pwd):/work" thumbsupgallery/thumbsup /bin/sh -c "cd /work/ && thumbsup --config config.json"
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: build_output
  committer-from-gh: true
  keep-history: true
  github-token:  $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
notifications:
  email: false
